// @ts-check
import { defineConfig } from 'astro/config';
import preact from '@astrojs/preact';

export default defineConfig({
  site: 'https://thefreetools.eu',
  trailingSlash: 'always',
  // Sitemap is generated by src/pages/sitemap-*.xml.ts (with hreflang + lastmod).
  integrations: [preact()],
  build: {
    // Inline CSS (~4 KB gzip) so the first paint needs no extra request.
    inlineStylesheets: 'always',
  },
  prefetch: {
    prefetchAll: false,
    defaultStrategy: 'hover',
  },
});
