import type { GuideContent } from '../types';
import { parseAmount, toWords, type Amount, type Lang, type WordsOptions } from '../../tools/words/engine';

// Every amount in words below is generated by the engine, so the text always matches the tool.
const say = (lang: Lang, n: string, o: Partial<WordsOptions>) =>
  toWords(lang, parseAmount(n, o.currency === 'KWD') as Amount, { currency: '', ...o });

const P = '2026-09-27';

export const wordsChequeEn: GuideContent = {
  key: 'words-cheque',
  tool: 'words',
  slug: 'how-to-write-amount-on-cheque',
  metaTitle: 'How to Write an Amount on a Cheque in Words (with Examples)',
  metaDescription:
    'Write the amount in words, the cents as a fraction of 100, then draw a line to the end. Examples for dollars, pounds and rupees, and the mistakes banks reject.',
  h1: 'How to write an amount on a cheque in words',
  answer:
    'Write the whole amount in words, then "and", then the cents as a fraction of 100, then the currency: $1,250.75 is "One thousand two hundred fifty and 75/100 dollars". Start at the far left of the line and draw a line through the unused space.',
  sections: [
    {
      heading: 'Examples',
      html: `<table><thead><tr><th>Amount</th><th>Written on the cheque</th></tr></thead><tbody>
<tr><td>$1,250.75</td><td>${say('en', '1250.75', { currency: 'USD', cheque: true })}</td></tr>
<tr><td>$500.00</td><td>${say('en', '500', { currency: 'USD', cheque: true })}</td></tr>
<tr><td>$19.99</td><td>${say('en', '19.99', { currency: 'USD', cheque: true })}</td></tr>
<tr><td>£2,040.50</td><td>${say('en', '2040.50', { currency: 'GBP', and: true })} only</td></tr>
<tr><td>₹1,25,000</td><td>${say('en', '125000', { currency: 'INR', only: true })}</td></tr></tbody></table>
<p>In the US the dollars are spelled out and the cents stay as a fraction. In the UK the pence are often written as digits after the words (<em>Two thousand and forty pounds 50p</em>) or in words as above. In India and Pakistan the amount uses lakh and crore and ends with <em>only</em>.</p>`,
    },
    {
      heading: 'Rules that stop a cheque being altered',
      html: `<ul>
<li>Start writing at the very left of the line, with a capital letter.</li>
<li>Draw a line from the last word to the end of the space: <em>Five hundred and 00/100 ——</em>.</li>
<li>Write <em>00/100</em> or <em>only</em> when there are no cents, so nothing can be added.</li>
<li>Hyphenate 21 to 99 (<em>forty-two</em>) and spell <em>forty</em> without a "u".</li>
<li>The words and the figures must match. If they don't, the Uniform Commercial Code (§ 3-114) says the words win in the US; many banks simply return the cheque.</li>
</ul>`,
    },
  ],
  faq: [
    {
      q: 'Do I write "and" before the cents?',
      a: 'Yes. On a US cheque "and" separates the dollars from the cents fraction, and it is the only place "and" appears: one thousand two hundred fifty and 75/100.',
    },
    {
      q: 'How do I write a cheque for less than one dollar?',
      a: 'Write "Zero and 75/100 dollars" and draw a line through the rest. Many people also write "Only seventy-five cents" to make it clear.',
    },
  ],
  published: P,
  updated: P,
};

export const wordsChequeEs: GuideContent = {
  key: 'words-cheque',
  tool: 'words',
  slug: 'como-escribir-cantidad-con-letra',
  metaTitle: 'Cómo escribir una cantidad con letra en cheques y facturas',
  metaDescription:
    'Escribe los pesos en letras y los centavos como fracción de 100: mil doscientos cincuenta pesos 75/100 M.N. Ejemplos para México, Colombia, Perú y España.',
  h1: 'Cómo escribir una cantidad con letra en cheques y facturas',
  answer:
    'Escribe la parte entera en letras, luego la moneda y los centavos como fracción de 100. En México, 1250,75 se escribe "mil doscientos cincuenta pesos 75/100 M.N.". Los importes redondos llevan 00/100.',
  sections: [
    {
      heading: 'Ejemplos por país',
      html: `<table><thead><tr><th>Importe</th><th>Con letra</th></tr></thead><tbody>
<tr><td>México, $1.250,75</td><td>${say('es', '1250,75', { currency: 'MXN', letterCase: 'upper' })}</td></tr>
<tr><td>México, $21.000</td><td>${say('es', '21000', { currency: 'MXN', letterCase: 'upper' })}</td></tr>
<tr><td>Colombia, $3.000.000</td><td>${say('es', '3000000', { currency: 'COP', letterCase: 'upper' })}</td></tr>
<tr><td>Perú, S/ 1.250,75</td><td>${say('es', '1250,75', { currency: 'PEN', letterCase: 'upper' })}</td></tr>
<tr><td>España, 1.250,75 €</td><td>${say('es', '1250,75', { currency: 'EUR' })}</td></tr></tbody></table>
<p>En cheques y facturas de México, Colombia y Perú es habitual escribir todo en mayúsculas y cerrar el espacio sobrante con una línea o con guiones.</p>`,
    },
    {
      heading: 'Errores frecuentes',
      html: `<ul>
<li><strong>"Veintiuno pesos"</strong>: delante del sustantivo es <em>veintiún pesos</em>, y 21.000 es <em>veintiún mil</em>.</li>
<li><strong>"Un millón pesos"</strong>: si el millón va solo, lleva <em>de</em>: <em>un millón de pesos</em>; en cambio, <em>un millón quinientos mil pesos</em>.</li>
<li><strong>"Cien veinte"</strong>: de 101 a 199 se usa <em>ciento</em>: <em>ciento veinte</em>.</li>
<li><strong>"Dieciseis" sin tilde</strong>: se escribe <em>dieciséis</em>, igual que <em>veintidós</em>, <em>veintitrés</em> y <em>veintiséis</em>.</li>
</ul>
<p>Si el importe en letra y el importe en número no coinciden, la ley de títulos y operaciones de crédito de varios países (por ejemplo, el artículo 16 de la LGTOC en México) da prioridad a la cantidad escrita en letra.</p>`,
    },
  ],
  faq: [
    {
      q: '¿Qué significa M.N.?',
      a: 'Moneda nacional. Indica que el importe está en pesos mexicanos y no en dólares.',
    },
    {
      q: '¿Cómo se escriben los centavos?',
      a: 'En México y Perú, como fracción de 100 (75/100). En España y Colombia es más común escribirlos en letras: con setenta y cinco céntimos o centavos.',
    },
  ],
  published: P,
  updated: P,
};

export const wordsChequeAr: GuideContent = {
  key: 'words-cheque',
  tool: 'words',
  slug: 'how-to-write-cheque-amount-arabic',
  metaTitle: 'كيف تكتب المبلغ في الشيك بالحروف (التفقيط) مع أمثلة',
  metaDescription:
    'اكتب المبلغ بالحروف بين "فقط" و"لا غير"، مع تمييز صحيح: ريالاً، ريالات، ريال. أمثلة بالريال والدرهم والدينار، وأخطاء شائعة في كتابة الشيكات.',
  h1: 'كيف تكتب المبلغ في الشيك بالحروف',
  answer:
    'يُكتب المبلغ بالحروف بين كلمتي "فقط" و"لا غير"، ثم الهللات أو الفلوس بعد حرف الواو. مثلاً 1250.75 ريال: فقط ألف ومائتان وخمسون ريالاً سعودياً وخمس وسبعون هللة لا غير.',
  sections: [
    {
      heading: 'أمثلة',
      html: `<table><thead><tr><th>المبلغ</th><th>التفقيط</th></tr></thead><tbody>
<tr><td>1250.75 ريال</td><td>${say('ar', '1250.75', { currency: 'SAR', only: true })}</td></tr>
<tr><td>5000 ريال</td><td>${say('ar', '5000', { currency: 'SAR', only: true })}</td></tr>
<tr><td>2000 درهم</td><td>${say('ar', '2000', { currency: 'AED', only: true })}</td></tr>
<tr><td>13 ديناراً كويتياً و500 فلس</td><td>${say('ar', '13.500', { currency: 'KWD', only: true })}</td></tr>
<tr><td>250 جنيهاً</td><td>${say('ar', '250', { currency: 'EGP', only: true })}</td></tr></tbody></table>`,
    },
    {
      heading: 'أخطاء شائعة',
      html: `<ul>
<li><strong>"ألفان ريال"</strong>: الصحيح <em>ألفا ريال</em> بحذف النون لأنها مضافة، ومثلها <em>مائتا ريال</em>.</li>
<li><strong>"خمسة عشر ريال"</strong>: بعد 11 إلى 99 يأتي المعدود مفرداً منصوباً: <em>خمسة عشر ريالاً</em>.</li>
<li><strong>"ثلاث ريالات"</strong>: الأعداد من 3 إلى 10 تخالف المعدود، فالريال مذكر والعدد مؤنث: <em>ثلاثة ريالات</em>، أما الهللة فمؤنثة: <em>ثلاث هللات</em>.</li>
<li><strong>ترك فراغ بعد المبلغ</strong>: أغلق السطر بـ"لا غير" وارسم خطاً في المساحة الفارغة.</li>
</ul>
<p>إذا اختلف المبلغ المكتوب بالحروف عن المبلغ بالأرقام، فإن أنظمة الأوراق التجارية في دول الخليج، ومنها نظام الأوراق التجارية السعودي، تعتمد المبلغ المكتوب بالحروف.</p>`,
    },
  ],
  faq: [
    {
      q: 'هل يجب كتابة "فقط" و"لا غير"؟',
      a: 'ليست شرطاً قانونياً، لكنها عادة متبعة في الشيكات والفواتير حتى لا يُضاف شيء قبل المبلغ أو بعده.',
    },
    {
      q: 'هل أكتب "مائة" أم "مئة"؟',
      a: 'الاثنتان صحيحتان. "مائة" بالألف هي الأكثر استخداماً في الشيكات، و"مئة" هي الرسم الحديث.',
    },
  ],
  published: P,
  updated: P,
};
